# Generated by Django 6.1.1 on 2026-10-05 16:05

import core.validators
import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('slug', models.SlugField(blank=True, help_text='Parte final de la URL del proyecto. Si se deja vacía, sale del título.', max_length=170, unique=True, verbose_name='dirección web')),
                ('summary', models.CharField(help_text='Texto corto que se ve en la tarjeta.', max_length=300, verbose_name='resumen')),
                ('description', models.TextField(verbose_name='descripción')),
                ('category', models.CharField(blank=True, help_text='Ejemplo: Fachada · Residencial', max_length=80, verbose_name='categoría')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='ubicación')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año')),
                ('cover_image', models.ImageField(upload_to=projects.models.project_upload_path, validators=[core.validators.validate_image_file], verbose_name='imagen de portada')),
                ('cover_thumbnail', models.ImageField(blank=True, editable=False, upload_to=projects.models.project_upload_path, verbose_name='miniatura de portada')),
                ('cover_alt', models.CharField(help_text='Describe la foto para quien no puede verla.', max_length=150, verbose_name='texto alternativo de la portada')),
                ('is_published', models.BooleanField(default=False, help_text='Si no está marcado, es un borrador.', verbose_name='publicado')),
                ('is_featured', models.BooleanField(default=False, help_text='Se muestra en el inicio. Máximo 3.', verbose_name='destacado')),
                ('featured_order', models.PositiveSmallIntegerField(default=0, help_text='El número menor va primero.', verbose_name='orden entre destacados')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], default='image', editable=False, max_length=10, verbose_name='tipo')),
                ('file', models.FileField(help_text='Imagen (jpg, png, webp) o video (mp4, webm).', upload_to=projects.models.project_upload_path, validators=[core.validators.validate_media_file], verbose_name='archivo')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to=projects.models.project_upload_path, verbose_name='miniatura')),
                ('poster', models.ImageField(blank=True, help_text='Solo para videos: la imagen que se ve antes de reproducir.', upload_to=projects.models.project_upload_path, validators=[core.validators.validate_image_file], verbose_name='vista previa del video')),
                ('alt_text', models.CharField(help_text='Describe la imagen o el video para quien no puede verlo.', max_length=150, verbose_name='texto alternativo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'imagen o video',
                'verbose_name_plural': 'galería',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
