# Generated by Django 5.2.17 on 2026-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_old_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Si se desmarca, la categoría sale del inicio, del filtro de proyectos y del formulario. Sus proyectos siguen viéndose en "Todos".', verbose_name='mostrar en el sitio'),
        ),
    ]
