# Generated by Django 6.1.1 on 2026-10-06 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemodelArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('name', models.CharField(max_length=60, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='identificador')),
                ('price_per_m2', models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío, el sitio muestra "A cotizar".', max_digits=10, null=True, verbose_name='precio por m² (USD)')),
                ('is_other', models.BooleanField(default=False, help_text='Si está marcado, el formulario pide especificar el área.', verbose_name='es la opción "Otro"')),
                ('is_active', models.BooleanField(default=True, help_text='Las áreas inactivas no aparecen en el formulario.', verbose_name='activa')),
            ],
            options={
                'verbose_name': 'área a remodelar',
                'verbose_name_plural': 'áreas y precios',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('phone', models.CharField(max_length=30, verbose_name='teléfono')),
                ('area_other', models.CharField(blank=True, max_length=120, verbose_name='área especificada')),
                ('square_meters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='metros cuadrados')),
                ('price_per_m2_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio por m² usado (USD)')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío significa "A cotizar".', max_digits=12, null=True, verbose_name='estimado (USD)')),
                ('message', models.TextField(blank=True, max_length=1000, verbose_name='mensaje')),
                ('whatsapp_message', models.TextField(verbose_name='mensaje de WhatsApp')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('closed', 'Cerrado')], default='new', max_length=10, verbose_name='estado')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='quotes.remodelarea', verbose_name='área')),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
