# Generated by Django 5.2.17 on 2026-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_initial_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aceptó la política de privacidad'),
        ),
    ]
