# Generated by Django 5.2.17 on 2026-10-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_old_fields'),
        ('quotes', '0003_privacy_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='projects.projectcategory', verbose_name='tipo de remodelación'),
        ),
        migrations.AddField(
            model_name='quote',
            name='category_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='tipo (nombre al cotizar)'),
        ),
        migrations.AddField(
            model_name='remodelarea',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Tipo de remodelación en el que aparece esta área. Déjala vacía para que aparezca en todos los tipos (por ejemplo, Otro).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remodel_areas', to='projects.projectcategory', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='remodelarea',
            name='slug',
            field=models.SlugField(editable=False, max_length=70, unique=True, verbose_name='identificador'),
        ),
    ]
