# Generated by Django 5.2.17 on 2026-10-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_assign_area_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='has_photos',
            field=models.BooleanField(default=False, verbose_name='tiene fotos del espacio'),
        ),
        migrations.AddField(
            model_name='quote',
            name='location',
            field=models.CharField(blank=True, max_length=160, verbose_name='ubicación del espacio'),
        ),
        migrations.AddField(
            model_name='quote',
            name='needs_visit',
            field=models.BooleanField(default=False, help_text='La persona no sabe los metros cuadrados: sus áreas no tienen m² ni precio.', verbose_name='pide una visita'),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_other', models.CharField(blank=True, max_length=120, verbose_name='área especificada')),
                ('square_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='metros cuadrados')),
                ('price_per_m2_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio por m² usado (USD)')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío significa "A cotizar".', max_digits=12, null=True, verbose_name='subtotal (USD)')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_items', to='quotes.remodelarea', verbose_name='área')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote', verbose_name='cotización')),
            ],
            options={
                'verbose_name': 'área cotizada',
                'verbose_name_plural': 'áreas cotizadas',
                'ordering': ['id'],
            },
        ),
    ]
