# Generated by Django 5.2.17 on 2026-10-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_migrate_quote_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='area',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='area_other',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='price_per_m2_snapshot',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='square_meters',
        ),
        migrations.AlterField(
            model_name='quote',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vacío significa "A cotizar".', max_digits=12, null=True, verbose_name='estimado total (USD)'),
        ),
    ]
