# Generated by Django 5.2.17 on 2026-10-06 12:01

import core.validators
import django.core.validators
import site_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='mostrar en el sitio')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('intro', models.TextField(blank=True, verbose_name='introducción')),
                ('submit_text', models.CharField(max_length=40, verbose_name='texto del botón de envío')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='mostrar en el sitio')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='lema')),
            ],
            options={
                'verbose_name': 'pie de página',
                'verbose_name_plural': 'pie de página',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='mostrar en el sitio')),
                ('eyebrow', models.CharField(blank=True, max_length=120, verbose_name='antetítulo')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('body', models.TextField(blank=True, verbose_name='párrafo')),
                ('primary_cta_text', models.CharField(max_length=40, verbose_name='texto del botón principal')),
                ('secondary_cta_text', models.CharField(max_length=40, verbose_name='texto del botón secundario')),
                ('image', models.ImageField(blank=True, upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_image_file], verbose_name='imagen principal')),
                ('image_alt', models.CharField(blank=True, max_length=150, verbose_name='texto alternativo de la imagen')),
                ('video', models.FileField(blank=True, help_text='Opcional. Se reproduce en bucle y sin sonido en lugar de la imagen. Súbelo corto y ya comprimido; la imagen queda como vista previa.', upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_video_file], verbose_name='video')),
            ],
            options={
                'verbose_name': 'portada',
                'verbose_name_plural': 'portada',
            },
        ),
        migrations.CreateModel(
            name='ProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='mostrar en el sitio')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('intro', models.TextField(blank=True, verbose_name='introducción')),
                ('video', models.FileField(blank=True, upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_video_file], verbose_name='video recorrido')),
                ('video_poster', models.ImageField(blank=True, help_text='Imagen que se ve antes de reproducir.', upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_image_file], verbose_name='vista previa del video')),
            ],
            options={
                'verbose_name': 'proceso (encabezado)',
                'verbose_name_plural': 'proceso (encabezado)',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='mostrar en el sitio')),
                ('title', models.CharField(max_length=80, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'paso del proceso',
                'verbose_name_plural': 'pasos del proceso',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='mostrar en el sitio')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('instagram_link_text', models.CharField(max_length=60, verbose_name='texto del enlace a Instagram')),
                ('view_all_text', models.CharField(max_length=60, verbose_name='texto del botón "Ver todos"')),
            ],
            options={
                'verbose_name': 'proyectos (encabezado)',
                'verbose_name_plural': 'proyectos (encabezado)',
            },
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=70, verbose_name='título del sitio')),
                ('meta_description', models.CharField(blank=True, help_text='Texto que aparece debajo del título en Google. Máximo 160 caracteres.', max_length=160, verbose_name='descripción')),
                ('share_image', models.ImageField(blank=True, help_text='Se ve al compartir el sitio en WhatsApp o redes. Ideal: 1200 × 630 px.', upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_image_file], verbose_name='imagen para compartir')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='mostrar en el sitio')),
                ('title', models.CharField(max_length=80, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='mostrar en el sitio')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('intro', models.TextField(blank=True, verbose_name='introducción')),
            ],
            options={
                'verbose_name': 'servicios (encabezado)',
                'verbose_name_plural': 'servicios (encabezado)',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_initials', models.CharField(default='RP', help_text='Se muestran dentro del círculo cuando no hay logo.', max_length=4, verbose_name='iniciales')),
                ('brand_name', models.CharField(default='RP DISEÑO', max_length=60, verbose_name='nombre de la marca')),
                ('brand_subtitle', models.CharField(default='INTERIOR · ARQUITECTURA', max_length=80, verbose_name='subtítulo de la marca')),
                ('logo', models.ImageField(blank=True, help_text='Opcional. Reemplaza al círculo con iniciales.', upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_image_file], verbose_name='logo')),
                ('header_cta_text', models.CharField(default='Cotiza tu proyecto', max_length=40, verbose_name='texto del botón del encabezado')),
                ('accent_color', models.CharField(choices=[('#111111', 'Negro'), ('#8A5A3B', 'Terracota'), ('#3E4A3D', 'Verde oliva'), ('#5B6670', 'Pizarra')], default='#111111', help_text='Color de los botones principales y de los números de Servicios.', max_length=7, verbose_name='color de acento')),
                ('whatsapp_number', models.CharField(default='584127305964', help_text='A este número llegan las cotizaciones. Solo dígitos, con código de país.', max_length=15, validators=[django.core.validators.RegexValidator(message='Escribe el número en formato internacional, solo dígitos. Ejemplo: 584127305964', regex='^\\d{10,15}$')], verbose_name='número de WhatsApp')),
                ('whatsapp_display', models.CharField(default='0412 730 5964', help_text='Cómo se ve el número en el sitio.', max_length=30, verbose_name='WhatsApp como se muestra')),
                ('contact_email', models.EmailField(default='rpdesings05@gmail.com', max_length=254, verbose_name='correo de contacto')),
                ('instagram_handle', models.CharField(default='rpdesign_ve', help_text='Sin la @.', max_length=60, verbose_name='usuario de Instagram')),
                ('city', models.CharField(default='Caracas, Venezuela', max_length=80, verbose_name='ciudad')),
                ('price_note', models.TextField(default='Precio referencial en USD, sujeto a modificación tras visita técnica. También puede pagarse en bolívares a tasa BCV del día.', help_text='Se muestra debajo del estimado de la calculadora.', verbose_name='nota de precio')),
                ('max_square_meters', models.DecimalField(decimal_places=2, default=10000, max_digits=8, verbose_name='máximo de m² en la calculadora')),
            ],
            options={
                'verbose_name': 'configuración general',
                'verbose_name_plural': 'configuración general',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='mostrar en el sitio')),
                ('text', models.CharField(max_length=60, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades (franja)',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
