# Generated by Django 5.2.17 on 2026-10-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_slider_max_square_meters'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('terminos', 'Términos y condiciones'), ('privacidad', 'Política de privacidad')], editable=False, unique=True, verbose_name='dirección web')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('intro', models.TextField(blank=True, verbose_name='introducción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'página legal',
                'verbose_name_plural': 'páginas legales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('title', models.CharField(max_length=120, verbose_name='subtítulo')),
                ('body', models.TextField(help_text='Los saltos de línea se respetan en el sitio.', verbose_name='texto')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='site_content.legalpage', verbose_name='página')),
            ],
            options={
                'verbose_name': 'apartado',
                'verbose_name_plural': 'apartados',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
