# Generated by Django 5.2.17 on 2026-10-06 20:05

import core.validators
import django.core.validators
import site_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_initial_legal_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='whatsapp_display',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_whatsapp_button',
            field=models.BooleanField(default=True, help_text='Botón fijo en la esquina inferior derecha de todas las páginas.', verbose_name='mostrar el botón flotante de WhatsApp'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_greeting',
            field=models.CharField(default='Hola! quiero agendar una reunión', help_text='Texto que ya viene escrito cuando alguien pulsa el botón.', max_length=200, verbose_name='mensaje del botón flotante'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, help_text='Solo se usa si ningún proyecto tiene marcado "Mostrar en el hero". Lo normal es que el hero muestre las portadas de los proyectos.', upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_image_file], verbose_name='imagen de respaldo'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(blank=True, help_text='Opcional. Si se deja vacío, el hero no muestra título.', max_length=160, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='video',
            field=models.FileField(blank=True, help_text='Opcional, y también solo como respaldo. Se reproduce en bucle y sin sonido en lugar de la imagen. Súbelo corto y ya comprimido.', upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_video_file], verbose_name='video de respaldo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='584127305964', help_text='A este número llegan las cotizaciones. Solo dígitos, con código de país. En el sitio se muestra en formato internacional: +58 412 730 5964.', max_length=15, validators=[django.core.validators.RegexValidator(message='Escribe el número en formato internacional, solo dígitos. Ejemplo: 584127305964', regex='^\\d{10,15}$')], verbose_name='número de WhatsApp'),
        ),
    ]
