# Generated by Django 5.2.17 on 2026-10-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0009_specialty_corporativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['order'], 'verbose_name': 'especialidad', 'verbose_name_plural': 'especialidades (ya no se muestran en el sitio)'},
        ),
        migrations.AddField(
            model_name='herosection',
            name='show_primary_cta',
            field=models.BooleanField(default=True, verbose_name='mostrar el botón principal'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='show_secondary_cta',
            field=models.BooleanField(default=True, verbose_name='mostrar el botón secundario'),
        ),
    ]
