# Generated by Django 5.2.17 on 2026-10-09 13:31

import core.validators
import django.db.models.deletion
import site_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0010_hero_cta_switches'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='section',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='site_content.processsection'),
        ),
        migrations.AddField(
            model_name='service',
            name='section',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='site_content.servicessection'),
        ),
        migrations.AddField(
            model_name='servicessection',
            name='cta_text',
            field=models.CharField(default='Cotizar', help_text='Botón que aparece en cada tarjeta y lleva al formulario de contacto.', max_length=40, verbose_name='texto del botón de cada servicio'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='body_font',
            field=models.FileField(blank=True, help_text='Opcional. Formatos: woff2, woff, ttf u otf. Lo ideal es una fuente variable (un solo archivo con todos los grosores): con un archivo de un solo grosor, las negritas se ven peor. Debes tener licencia para usarla en la web. Vacío = fuente original del sitio.', upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_font_file], verbose_name='fuente de texto'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='heading_font',
            field=models.FileField(blank=True, help_text='Opcional. Formatos: woff2, woff, ttf u otf. Lo ideal es una fuente variable (un solo archivo con todos los grosores): con un archivo de un solo grosor, las negritas se ven peor. Debes tener licencia para usarla en la web. Vacío = fuente original del sitio.', upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_font_file], verbose_name='fuente de títulos'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_estimate',
            field=models.BooleanField(default=True, help_text='Si se desmarca, el visitante no ve ningún precio en el formulario ni en el mensaje de WhatsApp. El estimado se sigue guardando en cada cotización del panel.', verbose_name='mostrar el estimado de precio'),
        ),
        migrations.CreateModel(
            name='QuoteFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('name', 'Nombre'), ('phone', 'Teléfono'), ('email', 'Correo'), ('category', 'Tipo de remodelación'), ('location', 'Ubicación del espacio'), ('areas', 'Áreas a remodelar'), ('area_other', 'Especificar el área (opción Otro)'), ('square_meters', 'Metros cuadrados'), ('needs_visit', 'Casilla: no sé cuántos m² son'), ('message', 'Mensaje'), ('has_photos', 'Casilla: tengo fotos del espacio')], editable=False, max_length=30, unique=True, verbose_name='campo')),
                ('label', models.CharField(max_length=120, verbose_name='título')),
                ('placeholder', models.CharField(blank=True, help_text='Lo que se lee dentro del campo antes de escribir. Las casillas no lo usan.', max_length=120, verbose_name='texto de ejemplo')),
                ('order', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='orden')),
                ('section', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='site_content.contactsection')),
            ],
            options={
                'verbose_name': 'campo del formulario',
                'verbose_name_plural': 'campos del formulario',
                'ordering': ['order'],
            },
        ),
    ]
