# Generated by Django 5.2.17 on 2026-10-09 22:51

import core.validators
import site_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0013_form_field_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'servicio', 'verbose_name_plural': 'tarjetas de servicios'},
        ),
        migrations.AlterModelOptions(
            name='servicessection',
            options={'verbose_name': 'servicios', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto que se ve en la tarjeta del servicio. Opcional.', upload_to=site_content.models.site_upload_path, validators=[core.validators.validate_image_file], verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Describe la foto para quien no puede verla.', max_length=150, verbose_name='texto alternativo de la imagen'),
        ),
    ]
